### ISSUE TITLE
Test Case Data Not Displayed on Initial Edit Attempt

### ISSUE THREAD

**Issue by itz4blitz** [testomatio/app#1104]
### Bug Report

**Describe the bug**
When editing an existing test case, the first time it opens for editing, the test case appears empty. The user must close and reopen the test case in order to see the data for editing.

**To Reproduce**
1. Go to the test case management page.
2. Click on an existing test case to edit.
3. Observe that the test case appears empty upon the first attempt to open it for editing.
4. Close the test case editor.
5. Reopen the same test case for editing.
6. Notice that the data is now visible and editable.

**Expected behavior**
The test case should display all its data the first time it is opened for editing, without requiring the user to close and reopen it.

**Screenshots/Video**

https://github.com/user-attachments/assets/83cff0ea-dc27-4373-9f43-361f5152aacb

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Brave
- Browser Version: Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)](https://brave.com/latest/)
- Application: production

**Additional context**
No console log data generated in dev tools.

**Comment by littlefrontender** [comment]
@TetianaKhomenko CNR on beta, I think it was fixed

**Comment by TetianaKhomenko** [comment]
Hi @itz4blitz! Thanks for reporting the issue. The issue was re-tested and verified as fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment]
The issue reoccurs after the latest release.

**Comment by TetianaKhomenko** [comment]
The issue should be fixed in the upcoming release.

**Comment by TetianaKhomenko** [comment]
@littlefrontender the issue still re-produces when we create a test plan > launch it > edit a test

**Comment by TetianaKhomenko** [comment]
fixed
