### ISSUE TITLE
[Report] - Rewrite/mark Failed test as Passed if it passes on re-run

### ISSUE THREAD

**Issue by vpostaichuk** [testomatio/app#1256]
**Is your feature request related to a problem? Please describe.**
The problem is when a failed auto-test passes on re-run (a very popular feature for Selenium, Cypress, and Playwright) the test is considered as Passed. But not in the Testomat io dashboard. In the 'Testomat io' failed test remains Failed, even if it passed on re-run, making the report less accurate.

**Describe the solution you'd like**
Re-write (or remove) the Failed status and mark it as Passed. The Testomat io can rely on the test id assigned in the testomatio.

**Describe alternatives you've considered**

**Additional context**
Updated "Passed" status should be reflected in all the related places:
- List of runs including runs/groups (Status column)
- Run dashboard
- Report view

![Image](https://github.com/user-attachments/assets/eb179d2c-53a2-4b2c-8e27-3d9419c4275e)

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/app/issues/968

**Comment by JoSeBu1** [comment]
I have the same problem, if the test pass in a retry it is shown up as failed

**Comment by TetianaKhomenko** [comment]
related to https://github.com/testomatio/testomatio/issues/4966

**Comment by TetianaKhomenko** [comment]
Hi @vpostaichuk! Could you please try reporter version `2.0.1-beta.5-timetamp`?

**Comment by JoSeBu1** [comment]
@TetianaKhomenko I just tried it and the problem persists

**Comment by vpostaichuk** [comment]
@TetianaKhomenko the issue has been fixed in the version `2.0.1-beta.5-timestamp`. 
Also, I see that if a test fails 3 times (during the first try, then on retry  #1, and retry #2), it is displayed as 1 failed test, but not 3 as before. So LGTM
Thanks to the team, great job!

<img width="2092" alt="Image" src="https://github.com/user-attachments/assets/08be6e6f-34cc-4521-a441-8d621dad7b4b" />

**Comment by TetianaKhomenko** [comment]
@JoSeBu1, could you please provide more details on your automation setup? Also, logs and screenshots will be very useful.

**Comment by vpostaichuk** [comment]
Hey @TetianaKhomenko! I've found a case when the issue is still reproducible.
After the full run is finished on CI I get the report with the run id. Then I fix failed tests and re-run them on Github Actions CI by providing the testomat.io run ID as an input for workflow_dispatch. 
The issue in this case is reproducible, and the 'Failed' test status is not updated in this case. Instead, there are 2 instances of the same auto test in the report. The 1st one is 'Failed' and it is counted as failed in the report. The 2nd record is 'Passed' (after a fix on the new test run), and it is also counted as passed in the report.
Please refer to the screenshots for better understanding: 

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/2350f841-5f48-4ac6-845d-ab34adbff795" />

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/801062d4-e7b8-4e25-9784-12907a30f75b" />

**Comment by TetianaKhomenko** [comment]
Hi @vpostaichuk @JoSeBu1! We've published update that should fix the issue. Could you please check it on your side?

**Comment by vpostaichuk** [comment]
@TetianaKhomenko what version I need to use to test the fix?

**Comment by JoSeBu1** [comment]
Hi @TetianaKhomenko It was fixed for me for like a month ago or so.

**Comment by TetianaKhomenko** [comment]
@vpostaichuk you can try on your current version or use the latest version 2.3.6

**Comment by vpostaichuk** [comment]
@TetianaKhomenko @DavertMik The issue is still reproducible.

My actions on real project:
1. I created and started a mixed run for manual + auto tests.
2. Once the corresponding job is triggered on Github Actions, I cancelled it.
3. Then I manually started 3 jobs on Github Actions and provided the run id for each of them (from step 1).
4. All the results are pushed to the testomatio run as expected.
<img width="1193" height="834" alt="Image" src="https://github.com/user-attachments/assets/eae8cab4-c129-4d9e-a309-9dd8db4196a9" />

5. Then I fix all the failed tests and rerun all 3 jobs on Github Actions _again_ and provide the same run id for each of them 


**As a result** - all (Passed and Failed) are counted twice and some of them 3 times, as I re-run a few test suites multiple times. Also, auto tests that failed on 1st run and then passed on re-run are counted as both Passed + Failed. 
<img width="1828" height="828" alt="Image" src="https://github.com/user-attachments/assets/b1a68085-0e07-44e6-b734-e38f4b6524c7" />

The  report shows approx. 1300 tests, while it has only 550 or so.


For debugging:
The TESTOMATIO run_id = `c72c133a`;
Testomatio reporter v2.3.6 - see the screenshot above.

**Comment by catpetrychenko-rgb** [comment]
Hi, [vpostaichuk](https://github.com/vpostaichuk)! Thanks for reporting the issue. The issue was fixed and will be publised to production in the upcoming release.

https://github.com/user-attachments/assets/7f38f1c0-4442-4158-8f79-f306140eb871
